return {
    'tpope/vim-fugitive',
    enabled = require('core.enable_plugins').fugitive,
    cmd = {
        'G',
        'Git',
        'Ggrep',
        'Gclog',
        'Gllog',
        'Gcd',
        'Glcd',
        'Gedit',
        'Gsplit',
        'Gvsplit',
        'Gtabedit',
        'Gpedit',
        'Gdrop',
        'Gread',
        'Gwrite',
        'Gwq',
        'Gdiffsplit',
        'Gvdiffsplit',
        'Ghdiffsplit',
    },
}
